export const TOP_TEN_BY_PRODUCED = "TOP_TEN_BY_PRODUCED";
export const TOP_TEN_BY_PRODUCED_SUCCESS = "TOP_TEN_BY_PRODUCED_SUCCESS";
export const TOP_TEN_BY_PRODUCED_FAILS = "TOP_TEN_BY_PRODUCED_FAILS";

export const TOP_FIVE_BY_REJECTED = "TOP_FIVE_BY_REJECTED";
export const TOP_FIVE_BY_REJECTED_SUCCESS = "TOP_FIVE_BY_REJECTED_SUCCESS";
export const TOP_FIVE_BY_REJECTED_FAILS = "TOP_FIVE_BY_REJECTED_FAILS";

export const BOTTOM_FIVE_BY_PENDING = "BOTTOM_FIVE_BY_PENDING";
export const BOTTOM_FIVE_BY_PENDING_SUCCESS = "BOTTOM_FIVE_BY_PENDING_SUCCESS";
export const BOTTOM_FIVE_BY_PENDING_FAILS = "BOTTOM_FIVE_BY_PENDING_FAILS";

export const TOTAL_PRODUCED_BY_DATE = "TOTAL_PRODUCED_BY_DATE";
export const TOTAL_PRODUCED_BY_DATE_SUCCESS = "TOTAL_PRODUCED_BY_DATE_SUCCESS";
export const TOTAL_PRODUCED_BY_DATE_FAILS = "TOTAL_PRODUCED_BY_DATE_FAILS";